version: '3.8'

services:
  vue-test-website:
    image: umutayb/vue-test-site:latest
    restart: always
    ports:
      - "7457:8080"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
